export const FETCH_HOME_LOAN_REQUEST = 'FETCH_HOME_LOAN_REQUEST';
export const FETCH_HOME_LOAN_REQUEST_SUCCESS = 'FETCH_HOME_LOAN_REQUEST_SUCCESS';
export const FETCH_HOME_LOAN_REQUEST_FAILURE = 'FETCH_HOME_LOAN_REQUEST_FAILURE';
